### PR TITLE
Update the token message

### PR DESCRIPTION
**Pull request by beautywords**
[facebook](https://www.facebook.com/beautywords2016)
[twitter](https://twitter.com/beautywords2016)
[pantograph](https://profile.pantograph.app/communityId/5fe8d2bf0d17e2742dfd9eee)

Thank so much!

Sincerity

### CODE REVIEW

**Comment by beautywords** [comment]
Update the token.

Thanks !

**Review by beautywords — COMMENTED** [review]
Update the token.

Thank so much!
cám ơn nhiều nhiều!

**Comment by khaihkd** [comment]
wrong convention. all filename need are lowercase

**Comment by beautywords** [comment]
updated with new information, please check again. thanks!

**Comment by khaihkd** [comment]
merge from #166 (duplicate)

**Pull request closed without merging**
