### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by CryptoInvestingandEarning**

### CODE REVIEW

**Comment by khaihkd** [comment]
we reject because your file is the wrong convention

**Comment by CryptoInvestingandEarning** [comment]
Hi.
Thanks for your reply.
What sort of file does the logo need to be?

**Comment by CryptoInvestingandEarning** [comment]
Could you help me add a logo please?
I'm making this token to use for loyalty points and competitions on my
website. It's not a coin for listing or ICO or anything like that and will
never be sold but I still want it to reflect my website logo. Please help
me with this.
Thanks

**Comment by khaihkd** [comment]
@CryptoInvestingandEarning Please read README.MD file for more detail

**Pull request closed without merging**
