### PR TITLE
Cryptotipsfriends patch 2

### PR DESCRIPTION
**Pull request by cryptotipsfriends**

### CODE REVIEW

**Comment by thanhson1085** [comment]
You can create an issue to update the token info: https://github.com/tomochain/tokens/issues/new?assignees=thanhson1085%2C+khaihkd&labels=help+wanted&template=feature-request.md&title=

**Comment by cryptotipsfriends** [comment]
Oh ok thanks a lot dude, i just begging with tomo, see you soon


Cryptotipsfriends

**Comment by cryptotipsfriends** [comment]
And Please dude can you check if my link are ok, i try to edit yesterday.
Thank's have a nice sunday
Cryptotipsfr

Le dim. 8 mars 2020 à 10:32, Crypto Tipsfr <cryptotipsfr@gmail.com> a
écrit :

**Comment by thanhson1085** [comment]
Discuss on the issue https://github.com/tomochain/tokens/issues/47

**Pull request closed without merging**
