### PR TITLE
Logo updates 

### PR DESCRIPTION
**Pull request by ProfSoumya**
Logo update for sGOLD token

### CODE REVIEW

**Comment by khaihkd** [comment]
`0x139b47ec2ea0a132a35fb1f01fc529c9e08fe065.png` need inside `tokens` folder

**Comment by ProfSoumya** [comment]
> `0x139b47ec2ea0a132a35fb1f01fc529c9e08fe065.png` need inside `tokens` folder

corrected it sir

**Comment by khaihkd** [comment]
you need to remove the wrong file :(

**Comment by ProfSoumya** [comment]
> you need to remove the wrong file :(

doing it no problem sir:)

**Pull request closed without merging**
