### PR TITLE
0xd379ab8cc4e02574853783becf2c46bc00128658.json

### PR DESCRIPTION
**Pull request by pipesanh04**

### CODE REVIEW

**Comment by pipesanh04** [comment]
integration of Auricoin (RIC), the payment of the 10 Tomo I do from binance.

**Comment by khaihkd** [comment]
wrong filename convention

**Comment by pipesanh04** [comment]
the name has already been corrected, please check again

**Comment by pipesanh04** [comment]
@khaihkd  payment was made from binance, please check

**Comment by pipesanh04** [comment]
WhatsApp Image 2022-01-08 at 10 45 30

**Comment by pipesanh04** [comment]
transfer txid.

0x170e149eebbae81f447d785e181ff61274373d7399e9731cc1823a57852c16d9

**Comment by khaihkd** [comment]
Please rename logo filename. All in lowercase

**Comment by pipesanh04** [comment]
could check again

**Comment by khaihkd** [comment]
You need remove wrong image file

**Pull request closed without merging**
