### PR TITLE
Create 0xfb135ba63fc9ce153e72c300b5d45060394968bf.json

### PR DESCRIPTION
**Pull request by mStabe**

### CODE REVIEW

**Comment by mStabe** [comment]
mr @khaihkdI  already made my extraction request for the verification of my mStable BTC (MBTC) token, 0x945Facb997494CC2570096c74b5F66A3507330a1 that is my ERC20 contract,

Could you check it out and tell me if I'm missing something

**Comment by mStabe** [comment]
@thanhson1085 @khaihkd Can you help us review this pull request?

**Comment by khaihkd** [comment]
rejected.

**Comment by mStabe** [comment]
@khaihkd Because my withdrawal request was rejected, is there something that it does not comply with.?

**Comment by khaihkd** [comment]
1. this is not mbtc (https://coinmarketcap.com/currencies/mstable-btc/)
2. you are not mstable official or a team member

DO NOT try to scam us or our user

**Pull request closed without merging**
