### PR TITLE
Update Pomodoro token (POMO) image

### PR DESCRIPTION
**Pull request by PomodoroToken**

### CODE REVIEW

**Comment by PomodoroToken** [comment]
Please explain what is wrong.

File name matches the requested format, i.e. 0x31e58cca9ecaa057edabaccff5abfbbc3443480c.png

**Comment by thanhson1085** [comment]
Check the link: https://github.com/tomochain/tokens/pull/42/files
You updated 3 files?

**Comment by thanhson1085** [comment]
You can create an issue https://github.com/tomochain/tokens/issues/new?assignees=thanhson1085%2C+khaihkd&labels=help+wanted&template=feature-request.md&title=

**Comment by PomodoroToken** [comment]
I see the issue. Forking the tomochain/tokens repo does not update my Pomodoro/tokens repo.
I'll raise an issue to update the token image instead.

Thank you.

**Pull request closed without merging**
