### PR TITLE
Token information update

### PR DESCRIPTION
**Pull request by ProfSoumya**
Logo update and token info update for sFuel token

### CODE REVIEW

**Comment by ProfSoumya** [comment]
Sir i have created this token in the mainnet..plz update the logo..thank u in advance

**Comment by khaihkd** [comment]
File name is incorrect. You need remove wrong file too

**Comment by ProfSoumya** [comment]
> File name is incorrect. You need remove wrong file too

Should i make a fresh upload .could u tell me which file is wrong? .json or the png?

**Comment by khaihkd** [comment]
All filename need in lower case. Remove file .png.png

**Comment by ProfSoumya** [comment]
all uppercase converted to lowercase as per your suggestion sir

**Comment by khaihkd** [comment]
You need delete all wrong files

**Comment by khaihkd** [comment]
Only accept mainnet token

**Pull request closed without merging**
