### PR TITLE
Update 0x190a31608B1DdBc115300344f897Beeb5Ef22856.json

### PR DESCRIPTION
**Pull request by bitcoincol**

### CODE REVIEW

**Comment by khaihkd** [comment]
- wrong file content (all in English)
- wrong filename

**Comment by khaihkd** [comment]
@bitcoincol please update

**Comment by bitcoincol** [comment]
OK thank you very much

**Comment by khaihkd** [comment]
@bitcoincol why don't you update content?

**Comment by bitcoincol** [comment]
Because it is the Colombian bitcoin, and in Colombia we speak Spanish and it is so that the bitcoin remains in the Spanish language, the same name says it Colombian Bitcoin

**Comment by khaihkd** [comment]
1. we have our standard, you cannot change
2. for language content you just change the second params. Something like this
```
{ 
    "symbol": " BTCOL " , 
    "name": " Bitcoin Colombiano " , 
    "description": " Bitcoin Colombia operate with no central authority or banks; managing transactions and the issuing of Bitcoin Colombia  is carried out collectively by the network.  nobody owns or controls BTCOL and everyone can take part. " , 
    "website": " http://www.bitcoincol.com.co/ " , 
    "communities": { 
        "email: " help@bitcoincol.org " , 
        " facebook": " https://www.facebook.com/Bitcoin-Colombiano-105198608242198 " , 
        "twitter": " https://twitter.com/BitcoinColombi4 " 
} 
```

**Comment by wbtcor** [comment]
this example that you gave me I can use

**Pull request closed without merging**
