### PR TITLE
Update Token Info GPXS

### PR DESCRIPTION
**Pull request by stablebank**
Hello, please add our token info to your blockchain

Thanks

### CODE REVIEW

**Comment by stablebank** [comment]
Hello, please help me long time back i updated my token info but not was made the pull request, please can add ourinformation.

**Comment by khaihkd** [comment]
@stablebank 
1. you cannot edit 2 files `blacklist.json` or `verified.json`
2. all filename need in lowercases

**Comment by stablebank** [comment]
Hello, thanks for your answer, ok I will update, sorry for edit blacklist is that we need to hide some tokens, can please explain me the procedure

**Comment by stablebank** [comment]
Hello, Files name changed, please help me with my info update, thanks

**Comment by stablebank** [comment]
Hello, please can help me

**Comment by khaihkd** [comment]
Still in `blacklist.json`

**Comment by stablebank** [comment]
Hello, I have removed our token    0x525d9a4977c5d3af10d1ab05e58a4593c661845f   of blacklisted file, 

Please help us to update our token info

**Comment by stablebank** [comment]
Hello, tell me that procedure I must to do for to update our token info

**Pull request merged**
